<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\View;
use TCPDF;

class JobCardController extends Controller
{
    public function generateJobCardPDF()
    {
        $path = storage_path('app/data/jobcard.json');
        if (!file_exists($path)) {
            return response()->json(['error' => 'JSON file nahi mili! Change the path if necessary.'], 404);
        }
        $jsonData = file_get_contents($path);
        $allData = json_decode($jsonData, true);
        $html = View::make('jobcard', [
            'labels' => $allData['labels'],
            'data'   => $allData['data']
        ])->render();
        $pdf = new \TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);
        $pdf->SetCreator('Wellpack System');
        $pdf->SetAuthor('Wellpack Printing');
        $pdf->SetTitle('Job Card - ' . $allData['data']['job_info']['job_card_no']);
        $pdf->SetMargins(12, 3, 12);
        $pdf->setPrintHeader(false);
        $pdf->setPrintFooter(false);
        $pdf->SetAutoPageBreak(TRUE, 10);
        $pdf->SetFont('freeserif', '', 10);
        $pdf->AddPage();
        $pdf->writeHTML($html, true, false, true, false, '');
        return $pdf->Output('Job_Card_' . $allData['data']['job_info']['job_card_no'] . '.pdf', 'I');
    }
    // public function generateEmployeePDF()
    // {
    //     $path = storage_path('app/data/employee_data.json');

    //     if (!file_exists($path)) {
    //         return response()->json(['error' => 'JSON file nahi mili!'], 404);
    //     }

    //     $jsonData = file_get_contents($path);
    //     $allData = json_decode($jsonData, true);

    //     $html = view('employee_report', [
    //         'employees' => $allData['data']
    //     ])->render();

    //     $pdf = new \TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);
    //     $pdf->SetCreator('Wellpack System');
    //     $pdf->SetTitle('Employee Registration Report');

    //     $pdf->SetMargins(10, 10, 10);
    //     $pdf->setPrintHeader(false);
    //     $pdf->setPrintFooter(false);
    //     $pdf->SetAutoPageBreak(TRUE, 15);
    //     $pdf->SetFont('freeserif', '', 10);
    //     $pdf->AddPage();

    //     $pdf->Rect(5, 5, 200, 287, 'D');

    //     $pdf->writeHTML($html, true, false, true, false, '');

    //     return $pdf->Output('Employee_Report_' . date('Y-m-d') . '.pdf', 'I');
    // }
    public function generateEmployeePDF()
    {
        $path = storage_path('app/data/student_data.json');
        if (!file_exists($path)) {
            return response()->json(['error' => 'JSON file nahi mili!'], 404);
        }

        $jsonData = file_get_contents($path);
        $allData = json_decode($jsonData, true);

        $html = view('student_report', ['employees' => $allData['data']])->render();

        $pdf = new class('P', 'mm', 'A4', true, 'UTF-8', false) extends \TCPDF {
            public function Header()
            {
                $this->Rect(5, 5, 200, 287, 'D');

                // $logo = public_path('images/profile.png');
                // if (file_exists($logo)) {
                //     $this->Image($logo, 43, 7, 18);
                // }


                $this->SetFont('helvetica', 'B', 14);
                $this->SetXY(39, 8);
                $this->Cell(0, 10, 'Demo PDF Generated Using Laravel (TCPDF)', 0, 0, 'C');

                $this->Line(10, 19, 200, 19);
                $this->Line(10, 20, 200, 20);

                $this->SetFont('helvetica', 'B', 14);
                $this->SetY(21);
                $this->Cell(0, 10, 'Student Registration Report', 0, 0, 'C');
            }

            public function Footer()
            {
                $this->Rect(5, 5, 200, 287, 'D');
                $this->SetY(-19);
                $this->Line(10, $this->GetY(), 200, $this->GetY());
                $this->Ln(1);
                $this->Line(10, $this->GetY(), 200, $this->GetY());
                $createdAt   = date('l, F j, Y, g:i A');
                $generatedBy = "Admin";
                $this->SetXY(10, $this->GetY() + 2);
                $this->SetFont('helvetica', '', 8);
                $this->Cell(15, 4, 'Created At:', 0, 0, 'L');
                $this->SetFont('helvetica', 'B', 8);
                $this->Cell(60, 4, $createdAt, 0, 1, 'L');
                $this->SetFont('helvetica', '', 8);
                $this->Cell(19, 4, 'Generated By:', 0, 0, 'L');
                $this->SetFont('helvetica', 'B', 8);
                $this->Cell(60, 4, $generatedBy, 0, 1, 'L');
                $this->SetFont('helvetica', '', 8);
                $this->SetY(-18);
                $this->Cell(0, 10, '© 2026 Wellpack. All Rights Reserved.', 0, 0, 'C');
                $this->Cell(12, 10, ' Page ' . $this->getAliasNumPage() . '/' . $this->getAliasNbPages(), 0, 0, 'R');
            }
        };

        $pdf->SetMargins(10, 35, 10);
        $pdf->SetAutoPageBreak(TRUE, 22);
        $pdf->SetFooterMargin(10);
        $pdf->AddPage();
        $pdf->SetFont('freeserif', '', 10);

        $pdf->writeHTML($html, true, false, true, false, '');

        return $pdf->Output('Student_Report.pdf', 'I');
    }
}
